#!/bin/bash
# fish - jfsc@cin.ufpe.br
# killing multiple processes
#
processtokill=$1
case $processtokill in
	[A-Za-z]*)
		$(ps aux |grep $processtokill | grep -v -e "grep" -e $0| awk '{print $2}'| while read CMD; do kill -9 $CMD; done;);
		Message="Process $processtokill killed."
  	;;
	*)
  		Message="Usage: $0 {service name}"
  	;;
esac

echo $Message;

